#include  <sys/time.h>
#include  <X11/Xlib.h>
#include  <X11/Xatom.h>
#include  <X11/Xutil.h>
#include  <GLES2/gl2.h>
#include  <EGL/egl.h>
#include <iostream>
#include <memory>
#include <vector>
#include <map>
#include <algorithm>
